lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: '%env(TOKEN_TTL)%'
    token_extractors:
        authorization_header:
            enabled: false
            prefix: Bearer
            name: Authorization
        cookie:
            enabled: true
            name: Bearer
    set_cookies:
        Bearer:
            lifetime: null
            samesite: lax
            path: /
            domain: null
            secure: '%env(bool:COOKIES_HTTPS)%'
            httpOnly: true
    remove_token_from_body_when_cookies_used: true
