version: '3.7'

services:
  symfony-example-db:
    image: mariadb:10.6.10
    command: --sql_mode=""
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - symfony-example_db_data:/var/lib/mysql

  symfony-example-php:
    build: docker/php-fpm
    working_dir: /app
    volumes:
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
      - .:/app:cached
    depends_on:
      - symfony-example-db

  symfony-example-nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app:cached
    depends_on:
      - symfony-example-php

volumes:
  symfony-example_db_data:
